// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        pgtype.UUID
	Title     string
	Content   string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Password     string
	RefreshToken string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
